p=int(input(""))
q=int(input(""))
print(f"{p} & {q}:",p & q)
print(f"{p} | {q}:",p | q)
print(f"{p} ^ {q}:",p ^ q)
print(f"~{p}:",~p)
print(f"~{q}:",~ q)
print(f"{p} >> {q}:",p >> q)
print(f"{p} << {q}:",p << q)
