p=int(input("Enter First number="))
q=int(input("Enter second number="))
print("Addition:",p+q)
print("Subtraction:",p-q)
print("Multiplication:",p*q)
print("Division:",p/q)
print("MOdulus:",p%q)
print("Floor division:",p//q)
print("Exponent:",p**q)
